# Generated by Django 4.2.7 on 2023-11-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_authors_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
